version: '3'
services:

  nginx:
    image: nginx
    ports:
      - "${MAIN_PORT:-9002}:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/nginx_cache"
      - "./static:/static:ro"
    restart: unless-stopped
  webapp:
    build: ./webapp
    volumes:
      - "./webapp:/webapp"
      - "./static:/webapp/dist"
      - "/webapp/node_modules"
      - "/webapp/v8-compile-cache-0"
    environment:
      - NODE_ENV
